minor fix

diff --git a/.github/workflows/update-cv.yaml b/.github/workflows/update-cv.yaml
--- a/.github/workflows/update-cv.yaml
+++ b/.github/workflows/update-cv.yaml
@@ -17,13 +17,29 @@ jobs:
       - name: Set up TeX Live + Python
         run: |
           sudo apt-get update
-          sudo apt-get install -y texlive-luatex texlive-latex-extra texlive-fonts-recommended
-          python3 --version
+          sudo apt-get install -y texlive-luatex texlive-latex-base texlive-latex-recommended
+
+      - name: Install Times New Roman font
+        run: |
+          sudo apt-get install software-properties-common -y
+          sudo add-apt-repository multiverse -y
+          sudo apt-get update
+
+          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
+          sudo apt-get install ttf-mscorefonts-installer -y
+
+          sudo fc-cache -f -v
+          
+
+      - name: verify fonts
+        run: |
+          ls /usr/share/fonts/truetype/msttcorefonts
+          fc-list | grep "Times New Roman" || echo "Font not found"
 
       - name: setup python
         uses: actions/setup-python@v2
         with:
-          python-version: 3.8 #install the python needed
+          python-version: 3.11
 
       - name: Build PDF
         run: source build.sh
